### ISSUE TITLE
如何使用参数化查询

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#221]
类似这种语句`SELECT XXX FROM myTable WHERE myID = @myID`
尝试这么写
```C#
var myID = 121;
fsql.Select<myTable>().Where(a => a.myID = myID).ToList(a=>new myTable());
```
好像生成出来的语句是 `SELECT XXX FROM myTable WHERE myID = 121`

不过 insert是可以参数化的。

**Comment by 2881099** [comment]
UseGenerateCommandParameterWithLambda

生成命令参数化执行，针对 lambda 表达式解析

**Comment by 2881099** [comment]
```csharp
    [ExpressionCall]
    public static class DbFunc
    {
        static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

        /// <summary>
        /// 设置表达式中的 string 参数化长度，优化执行计划
        /// </summary>
        /// <param name="that"></param>
        /// <param name="size"></param>
        /// <returns></returns>
        public static string SetDbParameter(this string that, int size)
        {
            if (context.Value.DbParameter != null)
            {
                //已经参数化了，开启了全局表达式参数化功能：UseGenerateCommandParameterWithLambda(true)
                context.Value.DbParameter.Size = size;
                return context.Value.ParsedContent["that"];
            }
            var guid = Guid.NewGuid().ToString("N").ToLower();
            context.Value.UserParameters.Add(new SqlParameter
            {
                ParameterName = guid,
                SqlDbType = System.Data.SqlDbType.VarChar,
                Size = size,
                Value = that
            });
            return $"@{guid}";
        }
    }
```

看看需不需要这个

**Comment by tky753** [comment]
还能这么优化，受教了🌞

**Comment by tky753** [comment]
@2881099  参数化查询，枚举有问题
```C#
public enum EDIUseMode : byte
{
    OutPut = 1,
    Import = 2,
    Both = 3,
}
[Table(Name = "EDI")]
public class Edi
{
    [Column(Name = "EDI_ID")]
    public long Id { get; set; }
    [Column(Name = "EDI_USE_MODE")]
    public EDIUseMode? UseMode { get; set; }
}
......
var um = EDIUseMode.Both;
await fsql.Select<Edi>()
    .Where(a => a.UseMode == um) //参数化查询枚举有问题
    .Take(10)
    .ToListAsync();

/*
报错 Requested value '@exp_0' was not found.
System.ArgumentException: Requested value '@exp_0' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseUInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, UInt32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, UInt32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value)
   at FreeSql.Internal.CommonExpression.ExpressionBinary(String oper, Expression leftExp, Expression rightExp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 493
*/
```

**Comment by 2881099** [comment]
应该是和 MapType 冲突
