### ISSUE TITLE
Inner Join  on f = (select top 1 xxx) 是否可行？

### ISSUE THREAD

**Issue by tky753** [2881099/FreeSql#228]
想实现这种语句
```sql
SELECT TOP 10 a.EDI_ID,b.EDII_ID FROM EDI a
INNER JOIN EDI_ITEM b ON b.EDII_ID = (
    SELECT TOP 1 c.EDII_ID FROM EDI_ITEM c
    WHERE a.EDI_ID = c.EDII_EDI_ID ORDER BY EDII_ID
    )
```
尝试这样写
```C#
[Table(Name = "EDI")]
public class Edi
{
    [Column(Name = "EDI_ID")] public long Id { get; set; }
}
[Table(Name = "EDI_ITEM")]
public class EdiItem
{
    [Column(Name = "EDII_ID")] public long Id { get; set; }
    [Column(Name = "EDII_EDI_ID")] public long EdiId { get; set; }
}
......
var sql = fsql.Select<Edi>()
    .From<EdiItem>((a, b) => a
        .InnerJoin(a1 => b.Id == 
         fsql.Select<EdiItem>().Where(c => c.EdiId == a1.Id)
             .OrderBy(c => c.Id).ToOne(c => c.Id)))
    .ToSql((a,b) => new
    {
        Id = a.Id,
        EdiId = b.Id
    });
```
报错
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Collections.ObjectModel.ReadOnlyCollection`1.get_Item(Int32 index)
   at FreeSql.SqlServer.SqlServerExpression.ExpressionLambdaToSqlOther(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 109
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1014
   at FreeSql.SqlServer.SqlServerExpression.<>c__DisplayClass1_0.<ExpressionLambdaToSqlOther>b__0(Expression exparg) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 19
   at FreeSql.SqlServer.SqlServerExpression.ExpressionLambdaToSqlOther(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 112
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1014
   at FreeSql.SqlServer.SqlServerExpression.<>c__DisplayClass1_0.<ExpressionLambdaToSqlOther>b__0(Expression exparg) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 19
   at FreeSql.SqlServer.SqlServerExpression.ExpressionLambdaToSqlOther(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 112
   at FreeSql.Internal.CommonExpression.ExpressionLambdaToSql(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\FreeSql\Internal\CommonExpression.cs:line 1014
   at FreeSql.SqlServer.SqlServerExpression.<>c__DisplayClass1_0.<ExpressionLambdaToSqlOther>b__0(Expression exparg) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 19
   at FreeSql.SqlServer.SqlServerExpression.ExpressionLambdaToSqlOther(Expression exp, ExpTSC tsc) in D:\Projects\github\FreeSql\Providers\FreeSql.Provider.SqlServer\SqlServerExpression.cs:line 112

**Comment by 2881099** [comment]
把子查询中的 ToOne 换成 First 试试

**Comment by 2881099** [comment]
```csharp
g.sqlite.Select<Edi, EdiItem>()
.InnerJoin((a,b) => b.Id == g.sqlite.Select<EdiItem>().As("c").Where(c => c.EdiId == a.Id).OrderBy(c => c.Id).First(c => c.Id))
.ToSql((a, b) => new
{
    Id = a.Id,
    EdiId = b.Id
});
```

**Comment by tky753** [comment]
成了。就改了个First。太厉害了，这都行👏

**Comment by 2881099** [comment]
表达式解析没有加 ToOne，我补上了
