### ISSUE TITLE
经常性出现“【主库】状态不可用”的异常

### ISSUE THREAD

**Issue by DeveloperOfChina** [2881099/FreeSql#86]
![image](https://user-images.githubusercontent.com/31717939/64243141-6ec4fd80-cf39-11e9-909f-9b4027187649.png)
使用VS调试，发现出现N多的 Select 1 的查询，不知道是什么问题？请大家指教！

**Comment by DeveloperOfChina** [comment]
![image](https://user-images.githubusercontent.com/31717939/64243385-d713df00-cf39-11e9-8e23-6422bbe70bf1.png)

**Comment by 2881099** [comment]
select 1时检测连接是否正常，一个时间段内没使用过会检测，一直在活跃的不有这个逻辑。

主库不可用，连接字符串正确吗？

另外：本地开发环境，max pool size设小一点，可以减少开销

**Comment by DeveloperOfChina** [comment]
数据库是可用的，并且是活跃的，同时因为还在开发阶段，所以对应查询的业务数据量非常少。期间曾换过数据库服务器，仍然出现同样的问题。而且经检测，出现该问题时，数据库才70+的连接数。
![image](https://user-images.githubusercontent.com/31717939/64304467-8397a480-cfbe-11e9-9731-84475c9ec0e7.png)
请问这个检测链接正常的功能是否可配置？

**Comment by 2881099** [comment]
是可用的，另外一个库也是类似的逻辑。

完整的错误信息是什么，贴出来看下

**Comment by DeveloperOfChina** [comment]
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=调用的目标发生了异常。
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at FreeSql.FreeSqlBuilder.Build[TMark]()
   at FreeSql.FreeSqlBuilder.Build()
   at ChooseShopSystem.Repositories.BaseRepository..ctor() in D:\Work\ChooseShopSystem\ChooseShopSystem.Repositories\BaseRepository.cs:line 36
   at ChooseShopSystem.Repositories.Transaction.UserTransaction..ctor()
   at ChooseShopSystem.Services.UserService..ctor() in D:\Work\ChooseShopSystem\ChooseShopSystem.Services\UserService.cs:line 21
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

内部异常 1:
Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。

**Comment by DeveloperOfChina** [comment]
我只有一个数据库，没做主从集群

**Comment by 2881099** [comment]
FreeSql.FreeSqlBuilder.Build() 这个用的单例注入的吗？改成单例

**Comment by 2881099** [comment]
max pool size=130，现在用的这个大小吧？开发环境可以设小一点，比如5个就好能增加启动速度

**Comment by jetydu** [comment]
我的好像也是经常出现这个问题

**Comment by DeveloperOfChina** [comment]
改成单例后的确能减少“检测连接”的请求数

**Comment by 2881099** [comment]
@jetydu @DeveloperOfChina 
用单例注入，设计就是这样，内部其实还是多例。

**Comment by jetydu** [comment]
我用的就是单例

**Comment by 2881099** [comment]
@jetydu 具体错误发出来分析

**Comment by DeveloperOfChina** [comment]
相关文档还是少了点。例如在生成实体类时，有导航属性和没有导航属性，对于同一个查询语句，最终生成的SQL语句是不一样的，这个细节不亲自使用是不会知道的。

**Comment by 2881099** [comment]
可能没留意文档吧，https://github.com/2881099/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%9f%a5%e8%af%a2%e7%9a%84%e6%95%b0%e6%8d%ae 这里有说明，导航属性查询太常用了，所以默认会把使用过的导航对象一起查出来

**Comment by DeveloperOfChina** [comment]
关问题了，谢谢 @2881099

**Comment by 2881099** [comment]
是否连接远程数据库？看下这个 https://github.com/2881099/FreeSql/issues/97

**Comment by DeveloperOfChina** [comment]
谢谢解答，我先测试一段时间

**Comment by goodluckily** [comment]
Mo too 俺也遇到了 ...

**Comment by 2881099** [comment]
> Mo too 俺也遇到了 ...

定义成单例，不要每次都 new Freesqlbuilder ().Build()

**Comment by DeveloperOfChina** [comment]
哦，之前问题不是因为单例导致的，应该是因为作者的线程缓存池的因素导致，必须在链接字符串中显式指定 Min Pool Size=1; Max Pool Size=5;
________________________________
发件人: 2881099 <notifications@github.com>
发送时间: 2020年12月30日 7:25
收件人: dotnetcore/FreeSql <FreeSql@noreply.github.com>
抄送: Hopefire <zhouhqtlxz@hotmail.com>; State change <state_change@noreply.github.com>
主题: Re: [dotnetcore/FreeSql] 经常性出现“【主库】状态不可用”的异常 (#86)


Mo too 俺也遇到了 ...

定义成单例，不要每次都 new Freesqlbuilder ().Build()

―
